export enum VehicleStatusEnum {
    AVAILABLE = "AVAILABLE",
    SOLD = "SOLD",
    IN_PREPARATION = "IN_PREPARATION",
    IN_MAINTENANCE = "IN_MAINTENANCE",
    IN_TEST_DRIVE = "IN_TEST_DRIVE",
    RESERVED = "RESERVED",
    OUT_OF_SERVICE = "OUT_OF_SERVICE",
}