services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clean_code
      MYSQL_USER: clean_code
      MYSQL_PASSWORD: clean_code
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
    db: