services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: cleanCode
    restart: always

volumes:
  data: