import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {CarFront, Construction, Home, Package, Users, Wallet, Wrench} from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    <div className="flex h-screen bg-gray-50">
        {/* Sidebar */}
        <aside className="w-64 bg-white border-r border-gray-200 shadow-sm p-4 flex flex-col gap-6">

            <img src="/triumph_logo.svg" alt="logo" className={"h-fit w-fit"}/>

            <nav className="flex flex-col gap-3">
                <Link
                    href="/dealers"
                    className="flex items-center gap-3 p-3 rounded-lg border border-gray-200 hover:bg-gray-50 hover:shadow transition"
                >
                    <Home className="w-5 h-5 text-gray-600"/>
                    <span className="text-sm font-medium text-gray-700">Concessionnaires</span>
                </Link>
                <Link
                    href="/inventory-spare-parts"
                    className="flex items-center gap-3 p-3 rounded-lg border border-gray-200 hover:bg-gray-50 hover:shadow transition"
                >
                    <Package className="w-5 h-5 text-gray-600"/>
                    <span className="text-sm font-medium text-gray-700">Pièces détachées</span>
                </Link>
                <Link
                    href="/drivers"
                    className="flex items-center gap-3 p-3 rounded-lg border border-gray-200 hover:bg-gray-50 hover:shadow transition"
                >
                    <Wallet className="w-5 h-5 text-gray-600"/>
                    <span className="text-sm font-medium text-gray-700">Conducteurs</span>
                </Link>
                <Link
                    href="/customers"
                    className="flex items-center gap-3 p-3 rounded-lg border border-gray-200 hover:bg-gray-50 hover:shadow transition"
                >
                    <Users className="w-5 h-5 text-gray-600"/>
                    <span className="text-sm font-medium text-gray-700">Clients</span>
                </Link>
                <Link
                    href="/vehicules"
                    className="flex items-center gap-3 p-3 rounded-lg border border-gray-200 hover:bg-gray-50 hover:shadow transition"
                >
                    <CarFront className="w-5 h-5 text-gray-600"/>
                    <span className="text-sm font-medium text-gray-700">Véhicules</span>
                </Link>
                <Link
                    href="/garages"
                    className="flex items-center gap-3 p-3 rounded-lg border border-gray-200 hover:bg-gray-50 hover:shadow transition"
                >
                    <Wrench className="w-5 h-5 text-gray-600"/>
                    <span className="text-sm font-medium text-gray-700">Garages</span>
                </Link>
                <Link
                    href="/maintenances"
                    className="flex items-center gap-3 p-3 rounded-lg border border-gray-200 hover:bg-gray-50 hover:shadow transition"
                >
                    <Construction className="w-5 h-5 text-gray-600"/>
                    <span className="text-sm font-medium text-gray-700">Maintenances</span>
                </Link>
            </nav>
        </aside>

        {/* Main Content */}
        <main className="flex-1 p-6 bg-gray-50 overflow-auto max-h-screen">
            <div className="bg-white border border-gray-200 rounded-xl shadow-sm p-6 min-h-full flex flex-col gap-3">
                {children}
            </div>
        </main>
    </div>
    </body>
    </html>
  );
}
