name: build.yml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '20'

    - run: npm install
      working-directory: backend
    - run: npm run build
      working-directory: backend

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '20'
    - run: npm install
      working-directory: backend
    - run: npm run test
      working-directory: backend
